### ISSUE TITLE
Ayuda no puedo compilar google-services.json 

### ISSUE THREAD

**Issue by cc546451** [jordyamc/Animeflv#762]
En Android Studio, importo el proyecto y me sale esto:

sync failed | 36s 740ms
-- | --
null |  
-- | --
C:/Users//Downloads/Animeflv-master |  
app/build.gradle |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :library. Open FileShow Details |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :library. Open FileShow Details |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :library. Open FileShow Details |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve project :library. Open FileShow Details |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve project :library. Open FileShow Details |  

Y bueno igual como soy novato en extremo pues que te diré xD le doy en edit configurations/gradle
Elijo el graddle project y en task pongo assemble le doy en run y me sale esto.
Executing tasks: [assemble]

Configuration on demand is an incubating feature.

> Configure project :app
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not resolve project :library.
     Required by:
         project :app
      > Unable to find a matching configuration of project :library: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
14:37:00: Task execution finished 'assemble'.

 No he modificado nada del codigo, que crees que pueda ser? como lo compilo? creeme investigue (o eso trate xD) pero sin resultados y por eso te lo consulto ahora. En fin gracias de antemano por la ayuda.

**Comment by jordyamc** [comment]
Es por que no eh subido un modulo de libreria, ahorita lo subo para que puedas actualizar tu fork

**Comment by jordyamc** [comment]
Acabo de subir la librería que falta https://github.com/jordyamc/Animeflv/commit/6f3df0dbc5328f7c02151d467a0ca4aa75cbeac4

**Comment by cc546451** [comment]
Gracias, ahora lo checo

**Comment by cc546451** [comment]
Y aqui estoy de nuevo xD ahora me sale esto > Task :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 4s
48 actionable tasks: 6 executed, 42 up-to-date
10:33:51: Task execution finished 'assemble'.

Y te adjunto esto.
Soy bastante lento para entender esto.
Si puedes indicarme que estoy haciendo mal te lo agradeceré
[manifest-merger-debug-report.txt](https://github.com/jordyamc/Animeflv/files/2236377/manifest-merger-debug-report.txt)
.

**Comment by jordyamc** [comment]
Necesitas el output del log
![captura](https://user-images.githubusercontent.com/6831873/43341312-b41dcec6-91a4-11e8-833a-a3079db1e215.PNG)

**Comment by cc546451** [comment]
Parece mala suerte, me quede sin luz en casa y me acaban de reconectar, asi que entro y ahora me sale asi, te refieres al que sale en la carpeta output?, compilé otra aplicación sin problemas supongo mi android studio esta bien, asi que puedo hacer?
![captura de pantalla de 2018-07-31 19-31-31](https://user-images.githubusercontent.com/41661962/43494528-e4a54270-94f8-11e8-81bc-fe301f933489.png)

**Comment by jordyamc** [comment]
Crea una entrada en strings.xml con el nombre one_signal_key
